version: '3'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    ports:
    - "80:80"
  
  nodeapp:
    build:
      context: ./
    container_name: nodeapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./database/init.sql:/data/application/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: skumbanan
  