version: '3'

services:
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    container_name: nginx
    ports:
    - "80:80"
  
  nodeapp:
    build:
      context: ./
    container_name: nodeapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nginx