// NameCommonGermanyOfficialFederalRepublicOfGermanyNativeNameDeuOfficialBundesrepublikDeutschlandCommonDeutschlandTLDDeCca2DECcn3276Cca3DEUCiocGERIndependentTrueStatusOfficiallyAssignedUnMemberTrueCurrenciesEURNameEuroSymbolIddRoot4Suffixes9CapitalBerlinAltSpellingsDEFederalRepublicOfGermanyBundesrepublikDeutschlandRegionEuropeSubregionWesternEuropeLanguagesDeuGermanTranslationsAraOfficialCommonCESOfficialSpolkovRepublikaNmeckoCommonNmeckoCymOfficialFederalRepublicOfGermanyCommonGermanyDeuOfficialBundesrepublikDeutschlandCommonDeutschlandEstOfficialSaksamaaLiitvabariikCommonSaksamaaFinOfficialSaksanLiittotasavaltaCommonSaksaFraOfficialRpubliqueFdraleDAllemagneCommonAllemagneHrvOfficialNjemakaFederativnaRepublikaCommonNjemakaHunOfficialNmetSzvetsgiKztrsasgCommonNmetorszgItaOfficialRepubblicaFederaleDiGermaniaCommonGermaniaJpnOfficialCommonKorOfficialCommonNldOfficialBondsrepubliekDuitslandCommonDuitslandPerOfficialCommonPolOfficialRepublikaFederalnaNiemiecCommonNiemcyPorOfficialRepblicaFederalDaAlemanhaCommonAlemanhaRusOfficialCommonSlkOfficialNemeckSpolkovRepublikaCommonNemeckoSPAOfficialRepblicaFederalDeAlemaniaCommonAlemaniaSweOfficialFrbundsrepublikenTysklandCommonTysklandUrdOfficialCommonZhoOfficialCommonLatlng519LandlockedFalseBordersAUTBELCZEDNKFRALUXNLDPOLCHEArea357114DemonymsEngFGermanMGermanFraFAllemandeMAllemandFlagMapsGoogleMapsHTTPSGooGlMapsMD9FBMq1NvXUBrkv6OpenStreetMapsHTTPSWWWOpenstreetmapOrgRelation51477Population83240525Gini2016319FifaGERCarSignsDYSideRightTimezonesUTC0100ContinentsEuropeFlagsPNGHTTPSFlagcdnCOMW320DePNGSVGHTTPSFlagcdnCOMDeSVGCoatOfArmsPNGHTTPSMainfactsCOMMediaImagesCoatsOfArmsDePNGSVGHTTPSMainfactsCOMMediaImagesCoatsOfArmsDeSVGStartOfWeekMondayCapitalInfoLatlng5252134PostalCodeFormatRegexD5.java

// Generated by https://quicktype.io

package com.fredoku.countryrestproxy.type;

import java.util.Map;

public class Country {
    private Name name;
    private String[] tld;
    private String cca2;
    private String ccn3;
    private String cca3;
    private String cioc;
    private boolean independent;
    private String status;
    private boolean unMember;
    private Currencies currencies;
    private Idd idd;
    private String[] capital;
    private String[] altSpellings;
    private String region;
    private String subregion;
    private Languages languages;
    private Map<String, Translation> translations;
    private long[] latlng;
    private boolean landlocked;
    private String[] borders;
    private long area;
    private Demonyms demonyms;
    private String flag;
    private Maps maps;
    private long population;
    private Gini gini;
    private String fifa;
    private Car car;
    private String[] timezones;
    private String[] continents;
    private CoatOfArms flags;
    private CoatOfArms coatOfArms;
    private String startOfWeek;
    private CapitalInfo capitalInfo;
    private PostalCode postalCode;

    public Name getName() { return name; }
    public void setName(Name value) { this.name = value; }

    public String[] getTLD() { return tld; }
    public void setTLD(String[] value) { this.tld = value; }

    public String getCca2() { return cca2; }
    public void setCca2(String value) { this.cca2 = value; }

    public String getCcn3() { return ccn3; }
    public void setCcn3(String value) { this.ccn3 = value; }

    public String getCca3() { return cca3; }
    public void setCca3(String value) { this.cca3 = value; }

    public String getCioc() { return cioc; }
    public void setCioc(String value) { this.cioc = value; }

    public boolean getIndependent() { return independent; }
    public void setIndependent(boolean value) { this.independent = value; }

    public String getStatus() { return status; }
    public void setStatus(String value) { this.status = value; }

    public boolean getUnMember() { return unMember; }
    public void setUnMember(boolean value) { this.unMember = value; }

    public Currencies getCurrencies() { return currencies; }
    public void setCurrencies(Currencies value) { this.currencies = value; }

    public Idd getIdd() { return idd; }
    public void setIdd(Idd value) { this.idd = value; }

    public String[] getCapital() { return capital; }
    public void setCapital(String[] value) { this.capital = value; }

    public String[] getAltSpellings() { return altSpellings; }
    public void setAltSpellings(String[] value) { this.altSpellings = value; }

    public String getRegion() { return region; }
    public void setRegion(String value) { this.region = value; }

    public String getSubregion() { return subregion; }
    public void setSubregion(String value) { this.subregion = value; }

    public Languages getLanguages() { return languages; }
    public void setLanguages(Languages value) { this.languages = value; }

    public Map<String, Translation> getTranslations() { return translations; }
    public void setTranslations(Map<String, Translation> value) { this.translations = value; }

    public long[] getLatlng() { return latlng; }
    public void setLatlng(long[] value) { this.latlng = value; }

    public boolean getLandlocked() { return landlocked; }
    public void setLandlocked(boolean value) { this.landlocked = value; }

    public String[] getBorders() { return borders; }
    public void setBorders(String[] value) { this.borders = value; }

    public long getArea() { return area; }
    public void setArea(long value) { this.area = value; }

    public Demonyms getDemonyms() { return demonyms; }
    public void setDemonyms(Demonyms value) { this.demonyms = value; }

    public String getFlag() { return flag; }
    public void setFlag(String value) { this.flag = value; }

    public Maps getMaps() { return maps; }
    public void setMaps(Maps value) { this.maps = value; }

    public long getPopulation() { return population; }
    public void setPopulation(long value) { this.population = value; }

    public Gini getGini() { return gini; }
    public void setGini(Gini value) { this.gini = value; }

    public String getFifa() { return fifa; }
    public void setFifa(String value) { this.fifa = value; }

    public Car getCar() { return car; }
    public void setCar(Car value) { this.car = value; }

    public String[] getTimezones() { return timezones; }
    public void setTimezones(String[] value) { this.timezones = value; }

    public String[] getContinents() { return continents; }
    public void setContinents(String[] value) { this.continents = value; }

    public CoatOfArms getFlags() { return flags; }
    public void setFlags(CoatOfArms value) { this.flags = value; }

    public CoatOfArms getCoatOfArms() { return coatOfArms; }
    public void setCoatOfArms(CoatOfArms value) { this.coatOfArms = value; }

    public String getStartOfWeek() { return startOfWeek; }
    public void setStartOfWeek(String value) { this.startOfWeek = value; }

    public CapitalInfo getCapitalInfo() { return capitalInfo; }
    public void setCapitalInfo(CapitalInfo value) { this.capitalInfo = value; }

    public PostalCode getPostalCode() { return postalCode; }
    public void setPostalCode(PostalCode value) { this.postalCode = value; }
}

class CapitalInfo {
    private double[] latlng;

    public double[] getLatlng() { return latlng; }
    public void setLatlng(double[] value) { this.latlng = value; }
}

class Car {
    private String[] signs;
    private String side;

    public String[] getSigns() { return signs; }
    public void setSigns(String[] value) { this.signs = value; }

    public String getSide() { return side; }
    public void setSide(String value) { this.side = value; }
}

class CoatOfArms {
    private String png;
    private String svg;

    public String getPNG() { return png; }
    public void setPNG(String value) { this.png = value; }

    public String getSVG() { return svg; }
    public void setSVG(String value) { this.svg = value; }
}

class Currencies {
    private Eur eur;

    public Eur getEur() { return eur; }
    public void setEur(Eur value) { this.eur = value; }
}

class Eur {
    private String name;
    private String symbol;

    public String getName() { return name; }
    public void setName(String value) { this.name = value; }

    public String getSymbol() { return symbol; }
    public void setSymbol(String value) { this.symbol = value; }
}

class Demonyms {
    private Eng eng;
    private Eng fra;

    public Eng getEng() { return eng; }
    public void setEng(Eng value) { this.eng = value; }

    public Eng getFra() { return fra; }
    public void setFra(Eng value) { this.fra = value; }
}

class Eng {
    private String f;
    private String m;

    public String getF() { return f; }
    public void setF(String value) { this.f = value; }

    public String getM() { return m; }
    public void setM(String value) { this.m = value; }
}

class Gini {
    private double the2016;

    public double getThe2016() { return the2016; }
    public void setThe2016(double value) { this.the2016 = value; }
}

class Idd {
    private String root;
    private String[] suffixes;

    public String getRoot() { return root; }
    public void setRoot(String value) { this.root = value; }

    public String[] getSuffixes() { return suffixes; }
    public void setSuffixes(String[] value) { this.suffixes = value; }
}

class Languages {
    private String deu;

    public String getDeu() { return deu; }
    public void setDeu(String value) { this.deu = value; }
}

class Maps {
    private String googleMaps;
    private String openStreetMaps;

    public String getGoogleMaps() { return googleMaps; }
    public void setGoogleMaps(String value) { this.googleMaps = value; }

    public String getOpenStreetMaps() { return openStreetMaps; }
    public void setOpenStreetMaps(String value) { this.openStreetMaps = value; }
}

class Name {
    private String common;
    private String official;
    private NativeName nativeName;

    public String getCommon() { return common; }
    public void setCommon(String value) { this.common = value; }

    public String getOfficial() { return official; }
    public void setOfficial(String value) { this.official = value; }

    public NativeName getNativeName() { return nativeName; }
    public void setNativeName(NativeName value) { this.nativeName = value; }
}

class NativeName {
    private Translation deu;

    public Translation getDeu() { return deu; }
    public void setDeu(Translation value) { this.deu = value; }
}

class Translation {
    private String official;
    private String common;

    public String getOfficial() { return official; }
    public void setOfficial(String value) { this.official = value; }

    public String getCommon() { return common; }
    public void setCommon(String value) { this.common = value; }
}

class PostalCode {
    private String format;
    private String regex;

    public String getFormat() { return format; }
    public void setFormat(String value) { this.format = value; }

    public String getRegex() { return regex; }
    public void setRegex(String value) { this.regex = value; }
}
