GET http://localhost:8080/api/customer/1

###
GET http://localhost:8080/api/customer/getAll
###
POST http://localhost:8080/api/customer/remove/1

###
POST http://localhost:8080/api/customer
Content-Type: application/json

{
  "firstName": "Jason",
  "lastName": "Karlson"
}